CREATE TABLE plan (
	id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	name TEXT NOT NULL,
	class_date DATE,
	warm_up TEXT,
	skills TEXT,
	notes TEXT,
	students TEXT,
	user_id INTEGER
		REFERENCES users(id) on delete cascade,
	folder_id INTEGER NOT NULL
		REFERENCES folder(id) on delete cascade,
	date_created TIMESTAMP DEFAULT now() NOT NULL
	);