INSERT INTO folder (name, user_id)
VALUES 
('ballet', 2),
('ballet', 3),
('ballet', 8),
('modern', 7),
('modern', 9),
('modern', 4),
('modern', 5),
('jazz', 1),
('jazz', 4),
('jazz', 5),
('jazz', 6),
('trapeze', 2),
('trap', 3),
('trap', 4),
('trap', 2),
('lyra', 1),
('lyra', 3),
('lyra', 5);